
#Oh My Goat Common Config
[General]
	#Whether to add the goat horn to the pillager outpost chest loot.
	add_outpost_loot = true
	#Whether to show tooltips for various items.
	show_tooltips = true

["Goat Cheese Making"]
	#How long it takes to make cheese.
	#Range: 10 ~ 1200
	cheese_making_duration = 600
	#Minimum amount of goat cheese you will get from cheese making.
	#Range: 0 ~ 64
	min_goat_cheese = 1
	#Maximum amount of goat cheese you will get from cheese making.
	#Range: 0 ~ 64
	max_goat_cheese = 1

["Horned Helmets"]
	#Probability to hurt the attacker when wearing a horned helmet.
	#Range: 0.0 ~ 1.0
	hurt_attacker_probability = 0.15
	#Probability to lose your horns when hurt someone with your horns.
	#Range: 0.0 ~ 1.0
	horn_losing_probability = 0.01
	#Probability to drop the horns when losing them.
	#Range: 0.0 ~ 1.0
	drop_horns_probability = 0.85

