
["World Generation"]
	#Enable generation of rocks
	enableRocks = true
	#Enable generation of twigs
	enableTwigs = true
	#Enable generation of fallen leaves
	enableFallenLeaves = true
	#Enable generation of bones
	enableBones = true
	#Enable generation of charred bones
	enableCharredBones = true
	#Enable generation of ice chunks
	enableIceChunks = true
	#Enable generation of pinecones
	enablePinecones = true
	#Enable generation of seashells
	enableSeashells = true
	#Enable generation of sea oats
	enableSeaOats = true
	#Enable generation of cattails
	enableCattails = true
	#Enable generation of beach grass
	enableBeachGrass = true
	#Enable generation of bark mushrooms
	enableBarkMushrooms = true
	#Enable generation of glowcap
	enableGlowcap = true
	#Enable generation of cindercane
	enableCindercane = true
	#Enable generation of nether nettles
	enableNetherNettles = true
	#Enable generation of short grass
	enableShortGrass = true
	#Enable generation of natural cobwebs
	enableNaturalCobwebs = true
	#Enable generation of small cacti
	enableSmallCacti = true
	#Enable generation of extra lilypads in lakes
	enableExtraLilypads = true
	#Enable generation of extra seagrass in lakes
	enableExtraSeagrass = true
	#Enable generation of extra grass in rivers
	enableExtraRiverGrass = true
	#Enable Palm Trees on beaches
	enablePalmTrees = true

["Biome Options"]
	#Enable Overgrown Spires biome
	enableOvergrownSpires = true
	#Enable Verdant Sands biome
	enableVerdantSands = true
	#Enable Boreal Forest biome
	enableBorealForest = true
	#Enable Snowy Boreal Forest biome
	enableSnowyBorealForest = true
	#Enable Pine Meadows biome
	enablePineMeadows = true
	#Enable Prairie biome
	enablePrairie = true
	#Enable Autumnal Coniferous Forest biome
	enableAutumnalConiferousForest = true
	#Enable Desert Shrubland biome
	enableDesertShrubland = true
	#Enable Redwoods biome
	enableRedwoods = true
	#Enable Snowy Redwoods biome
	enableSnowyRedwoods = true
	#Enable Baobab Fields biome
	enableBaobabFields = true
	#Enable Crystal Lakes biome
	enableCrystalLakes = true
	#Enable Blossoming Fields biome
	enableBlossomingFields = true

["Entity Options"]
	#Enable spawning of tropical fish in jungles
	enableJungleTropicalFish = true

